import pytest
import os
from bq_loader import create_table_from_local, create_table_from_bucket, upload_files_to_bucket


class Test_bq_loader:

    @pytest.mark.skip(reason='TODO')
    def test_create_table_from_local(self):
        create_table_from_local(table_id='test_bq_loader',
                                project_id='subugoe-collaborative',
                                dataset_id='resources',
                                file_path='test_data/7513.jsonl',
                                schema_file_path='test_schema/schema_crossref.json',
                                source_format='jsonl',
                                write_disposition='WRITE_EMPTY',
                                table_description='Test Table generated by bq_loader',
                                ignore_unknown_values=True)

    @pytest.mark.skip(reason='TODO')
    def test_create_table_from_local(self):
        create_table_from_local(table_id='test_bq_loader',
                                project_id='subugoe-collaborative',
                                dataset_id='resources',
                                file_path='test_data/',
                                schema_file_path='test_schema/schema_crossref.json',
                                source_format='jsonl',
                                write_disposition='WRITE_APPEND',
                                table_description='Test Table generated by bq_loader',
                                ignore_unknown_values=True)

    @pytest.mark.skip(reason='TODO')
    def test_create_table_from_bucket(self):
        create_table_from_bucket(uri='gs://bigschol/tests/*',
                                 table_id='bq_loader_test',
                                 project_id='subugoe-collaborative',
                                 dataset_id='resources',
                                 schema_file_path='test_schema/schema_crossref.json',
                                 source_format='jsonl',
                                 write_disposition='WRITE_EMPTY',
                                 table_description='Test Table generated by bq_loader',
                                 ignore_unknown_values=True)

    #@pytest.mark.skip(reason='TODO')
    def test_upload_files_to_bucket(self):
        upload_files_to_bucket(bucket_name='bigschol',
                               file_path='test_data/',
                               gcb_dir='tests')
