import pytest
import os
from bq_loader import create_table


class Test_bq_loader:

    @pytest.mark.skip(reason='TODO')
    def test_create_table(self):
        create_table(table_id='subugoe-collaborative.resources.test_bq_loader',
                     file_path='test_data/7513.jsonl',
                     schema_file='test_schema/schema_crossref.json',
                     source_format='jsonl',
                     write_disposition='WRITE_EMPTY',
                     destination_table_description='Test Table generated by bq_loader',
                     ignore_unknown_values=True)

    @pytest.mark.skip(reason='TODO')
    def test_create_table(self):
        create_table(table_id='subugoe-collaborative.resources.test_bq_loader',
                     file_path='test_data/',
                     schema_file='test_schema/schema_crossref.json',
                     source_format='jsonl',
                     write_disposition='WRITE_APPEND',
                     destination_table_description='Test Table generated by bq_loader',
                     ignore_unknown_values=True)
